path = "/home/niranjan/.espressif"
esp_idf_json_path = "/home/niranjan/.espressif/tools"
tool_download_folder_name = "/home/niranjan/.espressif/dist"
tool_install_folder_name = "/home/niranjan/.espressif/tools"
target = ["esp32s3"]
idf_versions = ["v5.3.5"]
tools_json_file = "tools/tools.json"
config_file_save_path = "/hdd/side_projects/esp32s3-slam/firmware/eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://dl.espressif.com/github_assets"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = false
skip_prerequisites_check = false
cleanup = false
python_env_folder_name = "python"
activation_script_path_override = "/home/niranjan/.espressif/tools"
python_version_override = "python313"
create_bat_activation_script = false

[idf_features_per_version]
"v5.3.5" = ["core", "gdbgui", "pytest", "ci", "docs", "ide"]

[idf_tools_per_version]
"v5.3.5" = ["xtensa-esp-elf-gdb", "xtensa-esp-elf", "esp-clang", "riscv32-esp-elf", "esp32ulp-elf", "openocd-esp32", "ninja", "esp-rom-elfs", "cmake"]
